language: python
python:
  - 2.7.12
install:
  - pip install -r advreport_test_project/requirements.txt
  - pip install mock==1.3.0
  - python setup.py develop
script:
  - coverage run --source=advanced_reports --omit='*migrations*' advreport_test_project/manage.py test
after_success: coveralls
