language: python
python:
  - 2.7
install:
  - pip install -r advreport_test_project/requirements.txt
  - python setup.py develop
script:
  - cd advreport_test_project
  - python manage.py test advanced_reports

